#' @title unpad_well
#'
#' @description Remove padding zeroes from a well name. Useful for compatibility with tables generated by the `plater` package.
#'
#' @param Well A Well name string
#' 
#' @return The same Well name, without zero-padding.
#'
#' @export
#'
#' @examples
#'
#' testmath(4)

unpad_well <- function(Well) {    #Remove padding zeros
    col = as.numeric(gsub("\\D", "", Well))
    row = gsub("\\d", "", Well)
    paste0(row, col)
}
