#' @title picklist
#'
#' @description Adds transfer rows of back-fill volume to a picklist generated by `picklist`. Returns original picklist with back-fill rows appended. All transfers in the picklist provided are assumed to take the same back-fill fluid
#'
#' @param pl picklist to add back-fill transfers to
#' 
#' @param backfill_wells Vector of wells containing back-fill fluid in source plate
#' 
#' @param src_plate_name Name of source plate containing the back-fill fluid, in case multiple source plates were used to generate the picklist
#'
#' @return A tibble containing back-filling coordinates for the picklist provided, bringing every well to the maximum volume in the picklist.
#'
#' @export
#'
#' @examples
#'
#' testmath(4)

#Create picklist for desired variable(s)
backfill <- function(pl, backfill_wells,
                     src_plate_name = "SrcPlateName", #Name of column containing plate name, if only 1 source plate is used, or name of Control plate if many
                     xfer_vol = "XferVol",
                     src_well = "SrcWell"){
    maxvol = max(pl[[xfer_vol]])
    pl2 = pl
    pl2[[xfer_vol]] = maxvol - pl2[[xfer_vol]]
    pl2 = pl2[pl2[[xfer_vol]] > 2.4,]
    pl2[[src_well]] = rep_len(backfill_wells, length.out=nrow(pl2))

    if (src_plate_name == "SrcPlateName"){ #Little loop to keep default source plate name
        if(length(unique(pl[[src_plate_name]])) == 1){
            pl2$SrcPlateName = unique(pl[[src_plate_name]])}
        else {stop("Multiple Source Plates given but none specified")}
    }
    else{ pl2$SrcPlateName = src_plate_name} # But to allow specifying a control source plate                        
    pl2 = rbind(pl, pl2)
    return(pl2)
}

