#' @title pad_well
#'
#' @description Add padding zeroes to a well name. Useful for compatibility with tables generated by the `plater` package.
#'
#' @param Well A Well name string
#' 
#' @return The same Well name, with zero-padding to the left of the number, to two digits.
#'
#' @export
#'
#' @examples
#'
#' testmath(4)

pad_well <- function(Well){   #Add padding 0 to make all well names the same length
    col = gsub("\\D", "", Well)
    row = gsub("\\d", "", Well)
    paste0(row, stringr::str_pad(col, 2, "left", "0"))
}

